### ISSUE TITLE
Unable to start the flow

### ISSUE THREAD

**Issue by ram1505** [GabrieleMaurina/node-red-contrib-machine-learning#3]
Hi,
Each time I click deploy, node-red terminates. Here is the output:

```
Welcome to Node-RED
===================

28 May 13:59:52 - [info] Node-RED version: v0.17.5
28 May 13:59:52 - [info] Node.js  version: v6.11.3
28 May 13:59:52 - [info] Linux 4.9.35-v7+ arm LE
28 May 13:59:53 - [info] Loading palette nodes
It looks like serialport didn't compile properly. This is a common problem and its fix is well documented here https://github.com/voodootikigod/node-serialport#to-install
The result of requiring the package is:  undefined
28 May 14:00:06 - [warn] ------------------------------------------------------
28 May 14:00:06 - [warn] [gpio] Missing serialport dependency
28 May 14:00:06 - [warn] [pythonshell] Error: Cannot find module './PythonshellNode' (line:19)
28 May 14:00:06 - [warn] ------------------------------------------------------
28 May 14:00:06 - [info] Settings file  : /home/pi/.node-red/settings.js
28 May 14:00:06 - [info] User directory : /home/pi/.node-red
28 May 14:00:06 - [info] Flows file     : /home/pi/.node-red/flows_pi.json
28 May 14:00:06 - [info] Creating new flow file
28 May 14:00:06 - [info] Version command failed
28 May 14:00:06 - [info] Server now running at http://127.0.0.1:1880/
28 May 14:00:06 - [info] Starting flows
28 May 14:00:06 - [info] Started flows
28 May 14:03:29 - [info] Stopping flows
28 May 14:03:29 - [info] Stopped flows
28 May 14:03:29 - [info] Starting flows
28 May 14:03:30 - [info] Started flows
28 May 14:03:30 - [red] Uncaught Exception:
28 May 14:03:30 - Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at Pipe.onread (net.js:568:26)
```

**Comment by GabrieleMaurina** [comment]
What's the flow you are trying to deploy?

**Comment by ram1505** [comment]
The sample flow given in the flows.nodered page. I'm using raspberry pi.

**Comment by ptondoh** [comment]
Hi,
What is the format to send by MQTT in your example?

**Comment by nuriyan** [comment]
Just tried the same.

Install Python and all dependencies on a fresh install.

I deployed the example flows as per instructed.  If the folders didnt exist by chance, would the flows error out and crash Node-Red?

22 Jul 01:23:43 - [info] Starting flows
22 Jul 01:23:43 - [info] Started flows
22 Jul 01:23:43 - [red] Uncaught Exception:
22 Jul 01:23:43 - Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at Pipe.onread (net.js:618:25)

**Comment by atraastrum** [comment]
I have the same problem as ram1505. Actually adding any single node from machine learning palette to flow and deploying triggers the error for me    

```
17 Sep 11:59:31 - [info] Starting flows
17 Sep 11:59:31 - [info] Started flows
17 Sep 11:59:31 - [red] Uncaught Exception:
17 Sep 11:59:31 - Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at Pipe.onread (net.js:628:25)
```
I have  
```
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

Running in the virtual machine

All python dependencies are installed 
```
node-red@bb-dev-instance:~$ pip3 list --format=columns |grep 'numpy\|pandas\|scikit'
numpy               1.15.1
pandas              0.23.4
scikit-learn        0.19.2
node-red@bb-dev-instance:~$
```

```
node-red@bb-dev-instance:~$ node -v
v8.10.0
node-red@bb-dev-instance:~$ npm list -g | grep red
└─┬ node-red@0.19.4
  │ ├── lodash.reduce@4.6.0
  │ │ │ ├── ordered-read-streams@1.0.1
  ├─┬ node-red-node-email@0.1.29
  ├─┬ node-red-node-feedparser@0.1.14
  ├── node-red-node-rbe@0.2.3
  ├─┬ node-red-node-twitter@1.1.2
node-red@bb-dev-instance:~$
```

**Comment by CWS-Pektin** [comment]
Same issue here, tried to use this nodes. Deployed them and boom. This error occours. Does anyone has an idea how to fix it?
