### ISSUE TITLE
Errors Running Sample Application

### ISSUE THREAD

**Issue by tonyc770** [GabrieleMaurina/node-red-contrib-machine-learning#6]
I am trying to run your sample application (Flow), but I get the following Error Message. Can you help?

Traceback (most recent call last):
  File "C:\Users\TContrada\node_modules\node-red-contrib-machine-learning\nodes\dataset\create-dataset/create-dataset.py", line 12, in <module>
    df = pandas.read_csv(config['path'], header=None)
  File "C:\Users\TContrada\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\TContrada\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\io\parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\TContrada\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\io\parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "C:\Users\TContrada\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\io\parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\TContrada\AppData...

**Comment by stavalfi** [comment]
We solved this error:
https://github.com/stavalfi/node-red-machine-learning-project


Look at the notes in the `README.md` file. No need to look at the source code.

**Comment by cjkini** [comment]
Hi guys,

I tried to run the example (https://flows.nodered.org/node/node-red-contrib-machine-learning). 
However, bumped into this error. : 
```
Traceback (most recent call last):
  File "/home/administrator/.node-red/node_modules/node-red-contrib-machine-learning/nodes/dataset/create-dataset/create-dataset.py", line 2, in <module>
    import pandas
ImportError: No module named 'pandas'
````
"Traceback (most recent call last):↵ File "/home/administrator/.node-red/node_modules/node-red-contrib-machine-learning/nodes/assessment/assessment.py", line 1, in <module>↵ import sklearn.metrics as m↵ImportError: No module named 'sklearn'`

I already install Sci-kit learn and pandas into my /home/administrator drive.

Any help please.

**Comment by miniwhen** [comment]
> Hi guys,
> 
> I tried to run the example (https://flows.nodered.org/node/node-red-contrib-machine-learning).
> However, bumped into this error. :
> 
> ```
> Traceback (most recent call last):
>   File "/home/administrator/.node-red/node_modules/node-red-contrib-machine-learning/nodes/dataset/create-dataset/create-dataset.py", line 2, in <module>
>     import pandas
> ImportError: No module named 'pandas'
> ```
> "Traceback (most recent call last):↵ File "/home/administrator/.node-red/node_modules/node-red-contrib-machine-learning/nodes/assessment/assessment.py", line 1, in ↵ import sklearn.metrics as m↵ImportError: No module named 'sklearn'`
> 
> I already install Sci-kit learn and pandas into my /home/administrator drive.
> 
> Any help please.

you need Python 3.6.4 or higher accessible by the command 'python' (on linux 'python3')
and install the pandas module

**Comment by smalhao** [comment]
Hello,
I need to start working with the machine learning library, is there any document explaining it with examples? i'm newbie in Node-RED, if anyone share a complete example that helps me.

**Comment by sakunaharinda** [comment]
Hi, Whenever I was trying to create and train a model with my own dataset the following error occurs from the trainer.What can I do? Any help please.
`Traceback (most recent call last):
  File "C:\Users\sakun\AppData\Roaming\SPB_Data\.node-red\node_modules\node-red-contrib-machine-learning\nodes\trainers\decision-tree-classifier/../trainer.py", line 20, in <module>
    df = pandas.read_json(data, orient='values')
  File "F:\Python3.8\lib\site-packages\pandas\util\_decorators.py", line 214, in wrapper
    return func(*args, **kwargs)
  File "F:\Python3.8\lib\site-packages\pandas\io\json\_json.py", line 608, in read_json
    result = json_reader.read()
  File "F:\Python3.8\lib\site-packages\pandas\io\json\_json.py", line 731, in read
    obj = self._get_object_parser(self.data)
  File "F:\Python3.8\lib\site-packages\pandas\io\json\_json.py", line 753, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "F:\Python3.8\lib\site-packages\pandas\io\json\_json.py", line 857, in parse
    self._parse_no_numpy()
  File "F:\Python3.8\lib\site-packages\pandas\io\json\_json.py", line 1107, in _parse_no_numpy
 ...`

**Comment by jinhui1951** [comment]
Recently I have installed all the above components for node-RED on MacOS. My python version is 3.7. When I have imported the test flow form GitHub (https://github.com/GabrieleMaurina/node-red-contrib-machine-learning/tree/master/test) and deployed it, red error icon appeared on left-bottom of all ML nodes, the following displayed as debug messages.
Traceback (most recent call last):
  File "~/.node-red/node_modules/node-red-contrib-machine-learning/nodes/dataset/create-dataset/create-dataset.py", line 2, in <module>
    import pandas
ImportError: No module named pandas

In fact, all the ML related modules are working well with standalone python.
$ python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> 

Is there anybody can advise what's wrong in my node-red/python configuration?

**Comment by Niushaeslamii** [comment]
Hello,
I am new in node-RED and I don't know how can I get information to import my csv database to this example: https://flows.nodered.org/node/node-red-contrib-machine-learning
when I import the library of ML to node-RED I have got lots of errors and I could not tp solve them 
could you help me for theses two problems ?
Thanks
